/**
 * MP7 personnel record — edit this file to update profile text.
 * Terminal logs stay in English. Character notes stay in Korean.
 */
const TIMING = {
  charDelay: 11,
  lineDelay: 160,
  bootStepDelay: 280,
  scrambleDuration: 460,
  specRevealDelay: 90,
};

const ENTITY = {
  designation: "MP7",
  codename: "UNSPECIFIED",
  gender: "여성",
  height: "155 cm",
  manufacturer: "Heckler & Koch",
  origin: "Germany",
  class: "Personal Defence Weapon",
  caliber: "4.6 × 30 mm",
  platform: "Compact weapon platform",
  mobility: "High mobility",
};

const BOOT_SEQUENCE = [
  { text: "[ ARMAMENT PERSONNEL ARCHIVE ]", cls: "hdr" },
  {
    text: "Initializing secure terminal...",
    cls: "sys",
    progress: 6,
    status: "INIT",
    channel: "OFFLINE",
  },
  { text: "Loading kernel modules .............. OK", cls: "dim", progress: 14 },
  {
    text: "Connecting to armament database...",
    cls: "sys",
    progress: 22,
    channel: "HANDSHAKE",
    status: "LINKING",
  },
  { text: "Secure channel: ONLINE", cls: "ok", progress: 34, channel: "ONLINE" },
  { text: "Verifying database integrity...", cls: "sys", progress: 42, status: "VERIFY" },
  { text: "Integrity check: PASS", cls: "ok", progress: 50 },
  { text: "Authenticating operator clearance...", cls: "sys", progress: 58, status: "AUTH" },
  { text: "Clearance: FIELD-ACCESS", cls: "ok", progress: 64 },
  { text: "Searching registered entities...", cls: "sys", progress: 72, status: "QUERY" },
  { text: "Query: MP7", cls: "prompt", progress: 78 },
  { text: "Entity found. Match count: 1", cls: "ok", progress: 84 },
  { text: "Decrypting personnel wrapper...", cls: "sys", progress: 90, status: "DECRYPTING" },
  { text: "Preparing visual ident and personnel interface...", cls: "sys", progress: 96 },
  { text: "ACCESS GRANTED.", cls: "ok hdr", progress: 100, status: "GRANTED" },
  { text: "PROFILE INTERFACE READY.", cls: "ok", progress: 100 },
];

const CATEGORIES = [
  {
    id: "basic",
    label: "BASIC INFORMATION",
    command: "query --category basic",
    processLines: [
      "Searching category: BASIC INFORMATION...",
      "Accessing encrypted record...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ BASIC INFORMATION ]",
      "지정명: MP7",
      "코드네임: UNSPECIFIED",
      "성별: 여성",
      "키: 155 cm",
      "제조: Heckler & Koch",
      "출신: Germany",
      "등급: Personal Defence Weapon",
      "구경: 4.6 × 30 mm",
      "플랫폼: Compact weapon platform / High mobility",
      "기타 인물 기록: STATUS: AWAITING OPERATOR INPUT",
    ],
  },
  {
    id: "personality",
    label: "PERSONALITY",
    command: "query --category personality",
    processLines: [
      "Searching category: PERSONALITY...",
      "Accessing behavioral archive...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ PERSONALITY DATA ]",
      "",
      "성격:",
      "",
      "겉으로는 무뚝뚝하고 말이 적다. 필요한 말만 하고, 감정은 잘 안 내보인다.",
      "",
      "차가워서라기보다 표현이 서툰 쪽에 가깝다. 알고 보면 귀여운 타입이다.",
      "",
      "평소엔 티가 거의 안 난다. 다만 부끄러우면 애써 태연한 척하면서 귀가 빨개진다. 시선도 잠깐 피하고, 대답이 더 짧아진다.",
      "",
      "속생각은 있는 편이지만, 오래 끌어가며 고민하는 성격은 아니다. 필요할 때 속으로 정리하고 넘긴다.",
      "",
      "먼저 말을 거는 편은 아니다. 그래도 불러서 대답을 안 하는 타입은 아니고, 그냥 답이 짧다.",
      "",
      "걱정되면 잔소리 대신 더 조용해진다. 아무 말 없이 옆에 남거나, 필요한 걸 슬쩍 건네고 넘어간다.",
      "",
      "가끔 던지는 짧은 한 마디가 농담일 때가 있다. 얼굴이 그대로라서, 처음엔 농담인지 잘 모른다.",
      "",
      "처음엔 좀 차갑게 느껴질 수 있다. 다만 가까워지면 무뚝뚝한 태도 아래로 작은 반응들이 보이기 시작한다. 한번 허용한 상대의 사소한 말은 잘 기억하는 편이다. 굳이 꺼내서 말하진 않는다.",
      "",
      "종합:",
      "",
      "겉은 담담하고, 속은 조금 여리다.",
      "",
      "오래 볼수록 차가운 사람이라기보다, 표현을 아끼는 사람에 가깝다. 본모습은 큰 일이 아니라, 귀가 붉어지는 순간 같은 빈틈에서 샌다.",
    ],
  },
  {
    id: "likes",
    label: "LIKES",
    command: "query --category likes",
    processLines: [
      "Searching category: LIKES...",
      "Parsing preference index...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ LIKES DATA ]",
      "",
      "좋아하는 것:",
      "",
      "사탕이랑 초콜릿. 단 음식은 거의 다 좋아한다. 티는 잘 안 내지만, 손에 쥐어 주면 거절은 잘 안 한다.",
      "",
      "귀여운 것. 큰 소리로 좋아하진 않는다. 그냥 시선이 잠깐 머물고, 나중에 혼자 다시 보게 된다.",
      "",
      "포근하고 따뜻한 장소. 넓고 번잡한 곳보다, 몸이 살짝 움츠려도 되는 작은 쪽이 편하다.",
      "",
      "정갈하게 정돈된 자리, 단정한 옷매무새, 작은 머리핀 같은 것도 은근히 좋아한다. 겉모습이 차가운 편이라 잘 안 보이는데, 취향 자체는 꽤 말랑하다.",
      "",
      "따뜻한 음료에 단 걸 곁들이는 것도 좋아한다. 다만 장갑을 끼고 있어서, 손이 끈적해지는 건 조금 신경 쓰는 눈치다.",
      "",
      "종합:",
      "",
      "좋아하는 건 대체로 작고 따뜻하다. 본인은 담담하게 굴지만, 그게 쌓이면 꽤 티가 난다.",
    ],
  },
  {
    id: "dislikes",
    label: "DISLIKES",
    command: "query --category dislikes",
    processLines: [
      "Searching category: DISLIKES...",
      "Parsing aversion index...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ DISLIKES DATA ]",
      "",
      "싫어하는 것:",
      "",
      "다리가 많은 벌레. 지네나 거미 쪽이 특히 그렇다. 표정은 잘 안 바뀌는데, 몸이 먼저 굳고 거리가 벌어진다.",
      "",
      "외로움. 말은 안 해도, 사람이 없어지는 건 오래 못 견딘다. 혼자 있는 건 괜찮아 보여도, 남겨지는 느낌은 아니다.",
      "",
      "너무 넓고 빈 곳도 질색이다. 불이 꺼진 큰 방처럼, 사람이 빠진 자리는 오래 버티지 못한다.",
      "",
      "종합:",
      "",
      "싫어하는 건 징그러운 것과, 혼자 남는 것이다. 벌레는 몸이 먼저 피하고, 외로움은 티를 안 내려 한다.",
    ],
  },
  {
    id: "traits",
    label: "TRAITS",
    command: "query --category traits",
    processLines: [
      "Searching category: TRAITS...",
      "Compiling distinguishing markers...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ TRAITS DATA ]",
      "",
      "특징:",
      "",
      "키가 크지 않다. 155 정도라, 존재감은 덩치가 아니라 분위기에서 나온다.",
      "",
      "은발 단발. 고개만 돌려도 머리카락이 가볍게 찰랑거린다. 정리는 크게 안 하는 편인데, 그래도 단정하게 떨어지는 쪽이다. 머리핀은 평소에도 그냥 꽂고 다닌다.",
      "",
      "중요한 자리가 아니면 편한 복장을 입는다. 제복은 필요할 때 입고, 평소엔 검은 후드에 흰 티, 반바지, 운동화 쪽이 더 자주 보인다.",
      "",
      "평소:",
      "",
      "벤치에 기대앉아 사탕을 물고 있는 모습이 이쪽에 가깝다. 한쪽 팔은 등받이에 걸치고, 다리는 편하게 뻗는다. 제복 때보다 어깨가 풀려 있다.",
      "",
      "말은 없어도 분위기는 덜 딱딱하다. 멀리서 보면 그냥 짧게 쉬고 있는 사람처럼 보인다.",
      "",
      "습관이 하나 있다. 좋아하는 걸 보면 빤히 바라본다. 본인은 그냥 보는 건데, 옆에서 보면 꽤 오래 본다.",
      "",
      "전투:",
      "",
      "넓은 공간에서 오래 붙잡는 타입은 아니다. 좁은 통로, 실내, 꺾인 모서리처럼 몸이 숨기 쉬운 곳에서 빠르게 들어간다.",
      "",
      "장점은 속도다. 먼저 위치를 잡고, 짧게 끊고, 바로 자리를 옮긴다. 한곳에 서서 맞받아치는 싸움은 잘 안 한다.",
      "",
      "덩치로 밀어붙이기보다, 작게 파고들어서 끝내는 쪽에 가깝다. 멀리서 오래 겨루기보다 가까이 붙었을 때 이야기가 빨라진다.",
      "",
      "종합:",
      "",
      "겉모습은 작고 단정하고, 평소엔 후드를 입고 느슨하다. 싸움은 짧고 빠르다. 시선이 오래 머무는 순간이 있으면, 그건 보통 마음에 든 것이다.",
    ],
  },
  {
    id: "relationships",
    label: "RELATIONSHIPS",
    command: "query --category relationships",
    processLines: [
      "Searching category: RELATIONSHIPS...",
      "Mapping linked entities...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ RELATIONSHIPS DATA ]",
      "STATUS: AWAITING OPERATOR INPUT",
      "관계 데이터가 등록되지 않았습니다.",
    ],
  },
  {
    id: "notes",
    label: "ADDITIONAL RECORDS",
    command: "query --category notes",
    processLines: [
      "Searching category: ADDITIONAL RECORDS...",
      "Opening unclassified annex...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ ADDITIONAL RECORDS ]",
      "",
      "대화:",
      "",
      "\"괜찮아?\"",
      "\"응.\"",
      "",
      "\"뭐 먹고 싶은 거 있어?\"",
      "\"단 거.\"",
      "\"단 거가 뭐.\"",
      "\"단 거.\"",
      "",
      "사탕을 내밀면 말은 없다. 고개만 아주 작게 끄덕이고 받는다. 나중에 \"고마워\"는 안 나온다. 대신 같은 자리에서 한 번 더 보게 된다.",
      "",
      "\"귀엽다.\"",
      "......",
      "(기록이 여기서 끊긴다. 촬영 담당 주석: 귀가 빨갰음. 본인은 모르는 척했음.)",
      "",
      "일어날 때, 아주 작게.",
      "\"...어디 가.\"",
      "먼저 가는 쪽이 되면 그 말은 안 한다. 남는 쪽에서만 나온다.",
      "",
      "주의:",
      "",
      "다리가 많은 벌레는 보여 주지 말 것. 설명하지 말 것. 사진도 안 됨. 본인은 \"괜찮다\"고 하는데, 몸이 이미 한 걸음 물러나 있다.",
      "",
      "오래 혼자 남겨 두지 말 것. 말은 안 한다. 다만 돌아왔을 때 시선이 조금 더 오래 붙는다.",
      "",
      "귀가 빨개졌다고 굳이 말하지 말 것. 말하면 다음 대답이 더 짧아진다. 최단 기록은 \"...\" 이다.",
      "",
      "메모:",
      "",
      "사탕을 좋아하면서 손이 끈적해지는 건 싫어한다. 장갑을 낀 채로 포장지를 아주 정석대로 벗기는 장면이 여러 번 목격됨.",
      "",
      "좋아하는 걸 보면 빤히 본다. 본인 변론: \"그냥 봤다.\" 주변 변론: \"1분 넘었음.\"",
      "",
      "건조한 한 마디가 농담일 때가 있다. 웃으면 귀가 조금 움직이는 경우가 있다. 안 웃으면 그냥 지나간다. 정답은 없는 듯하다.",
      "",
      "종합:",
      "",
      "말은 적고, 남는 건 시선이랑 사탕 포장지다. 차갑게 구는 날보다, 아무 말 없이 옆에 앉아 있는 날이 더 많다.",
    ],
  },
];
