/**
 * MP7 personnel record — edit this file to update profile text.
 * Terminal logs stay in English. Character notes stay in Korean.
 */
const TIMING = {
  charDelay: 11,
  lineDelay: 160,
  bootStepDelay: 280,
  scrambleDuration: 460,
  specRevealDelay: 90,
};

const AUTH = {
  password: "1031",
};

const CHARACTERS = [
  {
    id: "mp7",
    designation: "MP7",
    name: "Vera Klein",
    codename: "Sieben",
    status: "ONLINE",
    available: true,
    portrait: "./assets/mp7-character.jpg",
    summary: "PDW // Heckler & Koch",
  },
  {
    id: "viera",
    designation: "VIERA",
    name: "Viera Kriss",
    codename: "Kriss",
    status: "PARTIAL",
    available: true,
    portrait: "./assets/viera-ident.jpg",
    summary: "AWAITING OPERATOR INPUT",
  },
];

const EMPTY_ROSTER_SLOTS = 1;

const ENTITY = {
  designation: "MP7",
  name: "Vera Klein",
  codename: "Sieben",
  gender: "여성",
  height: "155 cm",
  manufacturer: "Heckler & Koch",
  origin: "Germany",
  class: "Personal Defence Weapon",
  caliber: "4.6 × 30 mm",
  platform: "Compact weapon platform",
  mobility: "High mobility",
};

const STILLS = [
  {
    id: "aug",
    code: "STILL 01",
    title: "AUG 언니와 놀러 간 날",
    image: "./assets/mp7-still-aug.jpg",
    rating: "field",
    command: "query --still aug",
    processLines: [
      "Searching visual log: STILL 01...",
      "Mounting attached still...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 01 ]",
      "",
      "기록:",
      "",
      "AUG 언니와 카페에 간 날이다. 음료는 하나고, 빨대는 하트 모양이다.",
      "",
      "본인은 끝까지 태연한 척한다. 다만 빨대를 무는 자세가 너무 성실해서, 태연함이 조금 무너진다.",
      "",
      "언니가 먼저 들이대면 거절은 잘 안 하는 편이다. 가까이 붙는 건 싫어한다기보다, 어떻게 해야 할지 모르는 쪽에 가깝다.",
      "",
      "카메라가 보이면 표정이 조금 날카로워진다. 놀러 간 건 맞는데, 찍히는 건 별개의 문제인 눈치다.",
      "",
      "종합:",
      "",
      "본인 진술: \"그냥 마셨다.\" 주변 진술: \"하트 빨대였다.\"",
    ],
  },
  {
    id: "cafe",
    code: "STILL 02",
    title: "혼자 카페에 간 날",
    image: "./assets/mp7-still-cafe.jpg",
    rating: "field",
    command: "query --still cafe",
    processLines: [
      "Searching visual log: STILL 02...",
      "Mounting attached still...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 02 ]",
      "",
      "기록:",
      "",
      "창가 자리다. 커피와 빵이 있다. 단 거라서 빵은 남기지 않을 가능성이 높다.",
      "",
      "혼자 온 날이다. 남겨진 느낌이 아니라, 자기가 앉은 쪽에 가깝다. 창밖을 오래 본다.",
      "",
      "좋아하는 걸 빤히 보는 습관이 여기선 거리 쪽으로 간다. 지나가는 차, 빛, 사람. 본인 변론은 또 \"그냥 봤다.\" 다.",
      "",
      "후드 대신 짧은 재킷과 체크 스커트다. 중요한 자리는 아닌데, 외출은 외출인지 옷이 조금 달라진다.",
      "",
      "종합:",
      "",
      "외로움이 아니라 혼자 있는 쪽에 가깝다. 창가에 오래 머무는 날이 가끔 있다.",
    ],
  },
  {
    id: "restricted-01",
    code: "STILL 03",
    title: "AUG 언니와 단둘이",
    image: "./assets/mp7-still-restricted-01.jpg",
    rating: "restricted",
    command: "query --still restricted-01",
    processLines: [
      "Searching visual log: STILL 03...",
      "Clearance check: RESTRICTED // 19+",
      "Mounting sealed still...",
      "Decrypting private notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 03 // RESTRICTED ]",
      "",
      "분류:",
      "",
      "19+ / 식별 화면 비공개 / 일반 탭 비공개",
      "",
      "기록:",
      "",
      "방은 어둡고, 자리만 좁다. 제복도 후드도 아니다.",
      "",
      "상대는 AUG 언니다. 안경은 그대로다. 본인은 끝까지 태연한 척한다. 다만 귀가 이미 빨개져 있다.",
      "",
      "카메라가 보이면 표정이 날카로워지던 날과는 다른 종류의 당황이다. 밀쳐내지는 않았다.",
      "",
      "본인 진술: 기록 거부.",
      "촬영 담당 주석: 거부는 됐으나, 파일은 남았음.",
      "",
      "종합:",
      "",
      "일반 식별과 GENERAL 탭에는 올라가지 않는다. 이 슬롯에서만 연다.",
    ],
  },
  {
    id: "restricted-02",
    code: "STILL 04",
    title: "그날이 있기 전.",
    image: "./assets/mp7-still-restricted-02a.jpg",
    images: [
      "./assets/mp7-still-restricted-02a.jpg",
      "./assets/mp7-still-restricted-02b.jpg",
    ],
    rating: "field",
    command: "query --still restricted-02",
    processLines: [
      "Searching visual log: STILL 04...",
      "Mounting linked stills...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 04 ]",
      "",
      "분류:",
      "",
      "선행 기록 / 컷 2",
      "",
      "기록:",
      "",
      "창가다. 비는 계속 온다. 같은 자리의 기록이 두 장이다. 옆으로 넘기면 다음 컷이 나온다.",
      "",
      "커피가 두 잔이다. 단 것도 있다. 손은 테이블 한가운데에서 만난다.",
      "",
      "본인은 언니가 잡으면 빼지 않는다. 표정도 잘 안 바뀐다. 다만 시선은 언니 쪽으로 가 있다.",
      "",
      "옷은 장마다 조금 다르다. 자리는 같다. 창밖의 빛만 조금 바뀐다.",
      "",
      "본인 진술: \"그냥 앉아 있었다.\"",
      "촬영 담당 주석: 손은 안 놓고 있었음.",
      "",
      "종합:",
      "",
      "아직 밖이다. 이후 기록과는 같은 흐름이지만, 여기까지는 창가에 머문다.",
    ],
  },
  {
    id: "train",
    code: "STILL 05",
    title: "어깨에 기대던 밤",
    image: "./assets/mp7-still-train.jpg",
    rating: "field",
    command: "query --still train",
    processLines: [
      "Searching visual log: STILL 05...",
      "Mounting attached still...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 05 ]",
      "",
      "기록:",
      "",
      "늦은 전철이다. 창밖은 불이고, 자리는 거의 비어 있다.",
      "",
      "본인은 언니 어깨에 기대 있다. 손은 잡고 있다. 눈은 떠 있다. 잠든 척인지, 그냥 기대는 건지 본인만 안다.",
      "",
      "언니는 창 쪽을 본다. 본인은 앞을 본다. 말은 없다.",
      "",
      "본인 진술: \"좀 쉬었다.\"",
      "촬영 담당 주석: 손은 안 놓고 있었음.",
      "",
      "종합:",
      "",
      "피곤한 날의 기록에 가깝다. 기대는 쪽은 늘 본인이다.",
    ],
  },
  {
    id: "aquarium",
    code: "STILL 06",
    title: "물고기 보러 간 날",
    image: "./assets/mp7-still-aquarium.jpg",
    rating: "field",
    command: "query --still aquarium",
    processLines: [
      "Searching visual log: STILL 06...",
      "Mounting attached still...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 06 ]",
      "",
      "기록:",
      "",
      "수족관이다. 유리가 파랗고, 물고기가 많다.",
      "",
      "본인은 유리 쪽을 본다. 좋아하는 걸 빤히 보는 습관이 여기선 물고기 쪽으로 간다. 손은 언니 허리를 잡고 있다.",
      "",
      "언니는 본인을 본다. 물고기는 안 보는 눈치다.",
      "",
      "본인 진술: \"물고기 봤다.\"",
      "주변 진술: \"언니는 안 보고 있었음.\"",
      "",
      "종합:",
      "",
      "본인은 수조를 보고, 언니는 본인을 본다. 붙잡는 쪽은 또 본인이다.",
    ],
  },
  {
    id: "bookstore",
    code: "STILL 07",
    title: "서점 데이트",
    image: "./assets/mp7-still-bookstore.jpg",
    rating: "field",
    command: "query --still bookstore",
    processLines: [
      "Searching visual log: STILL 07...",
      "Mounting attached still...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 07 ]",
      "",
      "기록:",
      "",
      "서점이다. 책이 펼쳐져 있다. 자리는 좁다.",
      "",
      "본인은 언니 쪽으로 기울어 같은 페이지를 본다. 언니는 책을 들고 있다. 본인은 손가락으로 한 줄을 짚는다.",
      "",
      "표정은 진지하다. 통로가 좁아서인지, 읽고 싶어서인지는 불명.",
      "",
      "본인 진술: \"글자 봤다.\"",
      "촬영 담당 주석: 책은 핑계일 가능성이 있음.",
      "",
      "종합:",
      "",
      "읽는 척은 성실하다. 거리는 통로 너비만큼만 비어 있다.",
    ],
  },
  {
    id: "icecream",
    code: "STILL 08",
    title: "단 거 들고 걷던 밤",
    image: "./assets/mp7-still-icecream.jpg",
    rating: "field",
    command: "query --still icecream",
    processLines: [
      "Searching visual log: STILL 08...",
      "Mounting attached still...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 08 ]",
      "",
      "기록:",
      "",
      "편의점 앞 밤길이다. 아이스크림이 두 단이다. 단 거라서 거절은 안 했을 가능성이 높다.",
      "",
      "손은 잡고 걷는다. 언니가 먼저 먹는다. 본인은 콘을 들고 표정이 진지하다.",
      "",
      "본인 진술: \"단 거.\"",
      "촬영 담당 주석: 본인 손에도 콘이 있었음. 녹기 전에 먹는 속도가 생각보다 빠름.",
      "",
      "종합:",
      "",
      "밤공기보다 단 게 우선이다. 걷는 동안 손은 안 놓는다.",
    ],
  },
  {
    id: "park",
    code: "STILL 09",
    title: "해 질 때까지",
    image: "./assets/mp7-still-park.jpg",
    rating: "field",
    command: "query --still park",
    processLines: [
      "Searching visual log: STILL 09...",
      "Mounting attached still...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 09 ]",
      "",
      "기록:",
      "",
      "공원 벤치다. 해가 진다. 말은 없다.",
      "",
      "본인은 언니 어깨에 기대 있다. 손은 잡고 있다. 다리는 편하게 뻗는다. 평소 벤치에 앉아 사탕 물던 자세와 닮아 있다. 옆자리만 다르다.",
      "",
      "본인 진술: \"앉았다.\"",
      "촬영 담당 주석: 일어나라는 말은 안 나왔음.",
      "",
      "종합:",
      "",
      "해가 질 때까지 그 자세다. 기대는 쪽은 또 본인이다.",
    ],
  },
  {
    id: "beach",
    code: "STILL 10",
    title: "손잡고 들어간 바다",
    image: "./assets/mp7-still-beach.jpg",
    rating: "field",
    command: "query --still beach",
    processLines: [
      "Searching visual log: STILL 10...",
      "Mounting attached still...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG // STILL 10 ]",
      "",
      "기록:",
      "",
      "바다다. 해는 지고, 신발을 들고 들어간다.",
      "",
      "손은 잡고 있다. 본인은 조금 작게 걷는다. 물이 발목에 닿아도 빼지 않는다.",
      "",
      "본인 진술: \"물 차가웠다.\"",
      "촬영 담당 주석: 그래도 안 놓고 들어갔음.",
      "",
      "종합:",
      "",
      "중요한 자리는 아닌데, 외출은 외출인지 옷이 달라진다. 바닷가에서도 손은 같다.",
    ],
  },
  {
    id: "sunflower",
    code: "SNAP 01",
    title: "해가 좋던 날",
    image: "./assets/mp7-track-sunflower.jpg",
    rating: "track",
    command: "query --snap sunflower",
    processLines: [
      "Searching track feed: SNAP 01...",
      "Pinning capture window...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ TRACK FEED // SNAP 01 ]",
      "",
      "기록:",
      "",
      "해가 좋다. 모자를 잡고 걷는다. 원피스가 바람에 조금 열린다.",
      "",
      "본인 진술: \"더웠다.\"",
      "촬영 담당 주석: 그래도 모자는 안 벗었음.",
    ],
  },
  {
    id: "fridge",
    code: "SNAP 02",
    title: "몰래 꺼내던 밤",
    image: "./assets/mp7-track-fridge.jpg",
    rating: "track",
    command: "query --snap fridge",
    processLines: [
      "Searching track feed: SNAP 02...",
      "Pinning capture window...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ TRACK FEED // SNAP 02 ]",
      "",
      "기록:",
      "",
      "밤이다. 냉장고가 열려 있다. 단 것만 보인다.",
      "",
      "본인 진술: \"조금.\"",
      "촬영 담당 주석: 조금이 선반 하나 분량.",
    ],
  },
  {
    id: "rooftop",
    code: "SNAP 03",
    title: "그냥 앉아 있던 오후",
    image: "./assets/mp7-track-rooftop.jpg",
    rating: "track",
    command: "query --snap rooftop",
    processLines: [
      "Searching track feed: SNAP 03...",
      "Pinning capture window...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ TRACK FEED // SNAP 03 ]",
      "",
      "기록:",
      "",
      "바람 부는 자리. 검은 옷. 부츠를 신고 앉아 있다.",
      "",
      "본인 진술: \"그냥 앉았다.\"",
      "촬영 담당 주석: 일어나라는 말은 안 나왔음.",
    ],
  },
  {
    id: "motorcycle",
    code: "SNAP 04",
    title: "해 지기 전에",
    image: "./assets/mp7-track-motorcycle.jpg",
    rating: "track",
    command: "query --snap motorcycle",
    processLines: [
      "Searching track feed: SNAP 04...",
      "Pinning capture window...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ TRACK FEED // SNAP 04 ]",
      "",
      "기록:",
      "",
      "해가 진다. 바이크 위에 앉아 있다. 말은 없다.",
      "",
      "본인 진술: \"타기 전이다.\"",
      "촬영 담당 주석: 시동은 아직.",
    ],
  },
  {
    id: "pool",
    code: "SNAP 05",
    title: "발만 담그고",
    image: "./assets/mp7-track-pool.jpg",
    rating: "track",
    command: "query --snap pool",
    processLines: [
      "Searching track feed: SNAP 05...",
      "Pinning capture window...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ TRACK FEED // SNAP 05 ]",
      "",
      "기록:",
      "",
      "물은 들어가고, 몸은 가장자리에 앉아 있다. 신발은 한 짝만 남았다.",
      "",
      "본인 진술: \"물에 다 안 들어갔다.\"",
      "촬영 담당 주석: 발은 이미 들어가 있음.",
    ],
  },
  {
    id: "maid",
    code: "SNAP 06",
    title: "파르페는 살렸다",
    image: "./assets/mp7-track-maid.jpg",
    rating: "track",
    command: "query --snap maid",
    processLines: [
      "Searching track feed: SNAP 06...",
      "Pinning capture window...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ TRACK FEED // SNAP 06 ]",
      "",
      "기록:",
      "",
      "트레이가 기운다. 체리는 떴다. 파르페는 아직 트레이 위에 있다.",
      "",
      "본인 진술: \"안 떨어뜨렸다.\"",
      "촬영 담당 주석: 체리만 예외.",
    ],
  },
];

const BOOT_SEQUENCE = [
  { text: "[ MEPIRIT ARCHIVE ]", cls: "hdr" },
  {
    text: "Initializing secure terminal...",
    cls: "sys",
    progress: 6,
    status: "INIT",
    channel: "OFFLINE",
  },
  { text: "Loading kernel modules .............. OK", cls: "dim", progress: 14 },
  {
    text: "Connecting to mepirit database...",
    cls: "sys",
    progress: 22,
    channel: "HANDSHAKE",
    status: "LINKING",
  },
  { text: "Secure channel: ONLINE", cls: "ok", progress: 34, channel: "ONLINE" },
  { text: "Verifying database integrity...", cls: "sys", progress: 42, status: "VERIFY" },
  { text: "Integrity check: PASS", cls: "ok", progress: 50 },
  { text: "Authenticating operator clearance...", cls: "sys", progress: 58, status: "AUTH" },
  { text: "Clearance: MEPIRIT-ACCESS", cls: "ok", progress: 64 },
  { text: "Searching registered entities...", cls: "sys", progress: 72, status: "QUERY" },
  { text: "Query: MP7", cls: "prompt", progress: 78 },
  { text: "Entity found. Match count: 1", cls: "ok", progress: 84 },
  { text: "Decrypting personnel wrapper...", cls: "sys", progress: 90, status: "DECRYPTING" },
  { text: "Preparing visual ident and personnel interface...", cls: "sys", progress: 96 },
  { text: "ACCESS GRANTED.", cls: "ok hdr", progress: 100, status: "GRANTED" },
  { text: "PROFILE INTERFACE READY.", cls: "ok", progress: 100 },
];

const CATEGORIES = [
  {
    id: "basic",
    label: "BASIC INFORMATION",
    command: "query --category basic",
    processLines: [
      "Searching category: BASIC INFORMATION...",
      "Accessing encrypted record...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ BASIC INFORMATION ]",
      "지정명: MP7",
      "본명: Vera Klein",
      "코드네임: Sieben",
      "성별: 여성",
      "키: 155 cm",
      "제조: Heckler & Koch",
      "출신: Germany",
      "등급: Personal Defence Weapon",
      "구경: 4.6 × 30 mm",
      "플랫폼: Compact weapon platform / High mobility",
      "기타 인물 기록: STATUS: AWAITING OPERATOR INPUT",
    ],
  },
  {
    id: "personality",
    label: "PERSONALITY",
    command: "query --category personality",
    processLines: [
      "Searching category: PERSONALITY...",
      "Accessing behavioral archive...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ PERSONALITY DATA ]",
      "",
      "성격:",
      "",
      "겉으로는 무뚝뚝하고 말이 적다. 필요한 말만 하고, 감정은 잘 안 내보인다.",
      "",
      "차가워서라기보다 표현이 서툰 쪽에 가깝다. 알고 보면 귀여운 타입이다.",
      "",
      "평소엔 티가 거의 안 난다. 다만 부끄러우면 애써 태연한 척하면서 귀가 빨개진다. 시선도 잠깐 피하고, 대답이 더 짧아진다.",
      "",
      "속생각은 있는 편이지만, 오래 끌어가며 고민하는 성격은 아니다. 필요할 때 속으로 정리하고 넘긴다.",
      "",
      "먼저 말을 거는 편은 아니다. 그래도 불러서 대답을 안 하는 타입은 아니고, 그냥 답이 짧다.",
      "",
      "걱정되면 잔소리 대신 더 조용해진다. 아무 말 없이 옆에 남거나, 필요한 걸 슬쩍 건네고 넘어간다.",
      "",
      "가끔 던지는 짧은 한 마디가 농담일 때가 있다. 얼굴이 그대로라서, 처음엔 농담인지 잘 모른다.",
      "",
      "처음엔 좀 차갑게 느껴질 수 있다. 다만 가까워지면 무뚝뚝한 태도 아래로 작은 반응들이 보이기 시작한다. 한번 허용한 상대의 사소한 말은 잘 기억하는 편이다. 굳이 꺼내서 말하진 않는다.",
      "",
      "종합:",
      "",
      "겉은 담담하고, 속은 조금 여리다.",
      "",
      "오래 볼수록 차가운 사람이라기보다, 표현을 아끼는 사람에 가깝다. 본모습은 큰 일이 아니라, 귀가 붉어지는 순간 같은 빈틈에서 샌다.",
    ],
  },
  {
    id: "likes",
    label: "LIKES",
    command: "query --category likes",
    processLines: [
      "Searching category: LIKES...",
      "Parsing preference index...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ LIKES DATA ]",
      "",
      "좋아하는 것:",
      "",
      "사탕이랑 초콜릿. 단 음식은 거의 다 좋아한다. 티는 잘 안 내지만, 손에 쥐어 주면 거절은 잘 안 한다.",
      "",
      "귀여운 것. 큰 소리로 좋아하진 않는다. 그냥 시선이 잠깐 머물고, 나중에 혼자 다시 보게 된다.",
      "",
      "포근하고 따뜻한 장소. 넓고 번잡한 곳보다, 몸이 살짝 움츠려도 되는 작은 쪽이 편하다.",
      "",
      "정갈하게 정돈된 자리, 단정한 옷매무새, 작은 머리핀 같은 것도 은근히 좋아한다. 겉모습이 차가운 편이라 잘 안 보이는데, 취향 자체는 꽤 말랑하다.",
      "",
      "따뜻한 음료에 단 걸 곁들이는 것도 좋아한다. 다만 장갑을 끼고 있어서, 손이 끈적해지는 건 조금 신경 쓰는 눈치다.",
      "",
      "종합:",
      "",
      "좋아하는 건 대체로 작고 따뜻하다. 본인은 담담하게 굴지만, 그게 쌓이면 꽤 티가 난다.",
    ],
  },
  {
    id: "dislikes",
    label: "DISLIKES",
    command: "query --category dislikes",
    processLines: [
      "Searching category: DISLIKES...",
      "Parsing aversion index...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ DISLIKES DATA ]",
      "",
      "싫어하는 것:",
      "",
      "다리가 많은 벌레. 지네나 거미 쪽이 특히 그렇다. 표정은 잘 안 바뀌는데, 몸이 먼저 굳고 거리가 벌어진다.",
      "",
      "외로움. 말은 안 해도, 사람이 없어지는 건 오래 못 견딘다. 혼자 있는 건 괜찮아 보여도, 남겨지는 느낌은 아니다.",
      "",
      "너무 넓고 빈 곳도 질색이다. 불이 꺼진 큰 방처럼, 사람이 빠진 자리는 오래 버티지 못한다.",
      "",
      "종합:",
      "",
      "싫어하는 건 징그러운 것과, 혼자 남는 것이다. 벌레는 몸이 먼저 피하고, 외로움은 티를 안 내려 한다.",
    ],
  },
  {
    id: "traits",
    label: "TRAITS",
    command: "query --category traits",
    processLines: [
      "Searching category: TRAITS...",
      "Compiling distinguishing markers...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ TRAITS DATA ]",
      "",
      "특징:",
      "",
      "키가 크지 않다. 155 정도라, 존재감은 덩치가 아니라 분위기에서 나온다.",
      "",
      "은발 단발. 고개만 돌려도 머리카락이 가볍게 찰랑거린다. 정리는 크게 안 하는 편인데, 그래도 단정하게 떨어지는 쪽이다. 머리핀은 평소에도 그냥 꽂고 다닌다.",
      "",
      "중요한 자리가 아니면 편한 복장을 입는다. 제복은 필요할 때 입고, 평소엔 검은 후드에 흰 티, 반바지, 운동화 쪽이 더 자주 보인다.",
      "",
      "평소:",
      "",
      "벤치에 기대앉아 사탕을 물고 있는 모습이 이쪽에 가깝다. 한쪽 팔은 등받이에 걸치고, 다리는 편하게 뻗는다. 제복 때보다 어깨가 풀려 있다.",
      "",
      "말은 없어도 분위기는 덜 딱딱하다. 멀리서 보면 그냥 짧게 쉬고 있는 사람처럼 보인다.",
      "",
      "습관이 하나 있다. 좋아하는 걸 보면 빤히 바라본다. 본인은 그냥 보는 건데, 옆에서 보면 꽤 오래 본다.",
      "",
      "전투:",
      "",
      "넓은 공간에서 오래 붙잡는 타입은 아니다. 좁은 통로, 실내, 꺾인 모서리처럼 몸이 숨기 쉬운 곳에서 빠르게 들어간다.",
      "",
      "장점은 속도다. 먼저 위치를 잡고, 짧게 끊고, 바로 자리를 옮긴다. 한곳에 서서 맞받아치는 싸움은 잘 안 한다.",
      "",
      "덩치로 밀어붙이기보다, 작게 파고들어서 끝내는 쪽에 가깝다. 멀리서 오래 겨루기보다 가까이 붙었을 때 이야기가 빨라진다.",
      "",
      "종합:",
      "",
      "겉모습은 작고 단정하고, 평소엔 후드를 입고 느슨하다. 싸움은 짧고 빠르다. 시선이 오래 머무는 순간이 있으면, 그건 보통 마음에 든 것이다.",
    ],
  },
  {
    id: "stills",
    label: "VISUAL LOG",
    command: "query --category stills",
    processLines: [
      "Searching category: VISUAL LOG...",
      "Indexing attached stills...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      "[ VISUAL LOG INDEX ]",
      "",
      "사진첩:",
      "",
      "이 기록은 식별 사진과 분리되어 있다. VISUAL LOG 화면에서 STILL 을 고르면 된다.",
      "",
      "GENERAL — 일반 스틸",
      "RESTRICTED — 19+ 스틸",
      "",
      "STILL 01 — AUG 언니와 놀러 간 날",
      "",
      "STILL 02 — 혼자 카페에 간 날",
      "",
      "STILL 03 — AUG 언니와 단둘이 // RESTRICTED",
      "",
      "STILL 04 — 그날이 있기 전. // 2 CUTS",
      "",
      "STILL 05 — 어깨에 기대던 밤",
      "",
      "STILL 06 — 물고기 보러 간 날",
      "",
      "STILL 07 — 서점 데이트",
      "",
      "STILL 08 — 단 거 들고 걷던 밤",
      "",
      "STILL 09 — 해 질 때까지",
      "",
      "STILL 10 — 손잡고 들어간 바다",
      "",
      "종합:",
      "",
      "제복/평소 식별 화면에는 올라가지 않는다. 19+ 기록은 RESTRICTED 탭에서만 연다.",
    ],
  },
  {
    id: "tracking",
    label: "SURVEILLANCE",
    command: "query --category surveillance",
    processLines: [
      "Searching category: SURVEILLANCE...",
      "Compiling field captures...",
      "Pinning track windows...",
      "Data stream established.",
    ],
    content: [
      "[ SURVEILLANCE BOARD ]",
      "",
      "TRACK.FEED 스냅만 핀한다. VISUAL LOG 와는 분리된 피드다.",
    ],
  },
  {
    id: "relationships",
    label: "RELATIONSHIPS",
    command: "query --category relationships",
    processLines: [
      "Searching category: RELATIONSHIPS...",
      "Mapping linked entities...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ RELATIONSHIPS DATA ]",
      "STATUS: AWAITING OPERATOR INPUT",
      "관계 데이터가 등록되지 않았습니다.",
    ],
  },
  {
    id: "notes",
    label: "ADDITIONAL RECORDS",
    command: "query --category notes",
    processLines: [
      "Searching category: ADDITIONAL RECORDS...",
      "Opening unclassified annex...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ ADDITIONAL RECORDS ]",
      "",
      "대화:",
      "",
      "\"괜찮아?\"",
      "\"응.\"",
      "",
      "\"뭐 먹고 싶은 거 있어?\"",
      "\"단 거.\"",
      "\"단 거가 뭐.\"",
      "\"단 거.\"",
      "",
      "사탕을 내밀면 말은 없다. 고개만 아주 작게 끄덕이고 받는다. 나중에 \"고마워\"는 안 나온다. 대신 같은 자리에서 한 번 더 보게 된다.",
      "",
      "\"귀엽다.\"",
      "......",
      "(기록이 여기서 끊긴다. 촬영 담당 주석: 귀가 빨갰음. 본인은 모르는 척했음.)",
      "",
      "일어날 때, 아주 작게.",
      "\"...어디 가.\"",
      "먼저 가는 쪽이 되면 그 말은 안 한다. 남는 쪽에서만 나온다.",
      "",
      "주의:",
      "",
      "다리가 많은 벌레는 보여 주지 말 것. 설명하지 말 것. 사진도 안 됨. 본인은 \"괜찮다\"고 하는데, 몸이 이미 한 걸음 물러나 있다.",
      "",
      "오래 혼자 남겨 두지 말 것. 말은 안 한다. 다만 돌아왔을 때 시선이 조금 더 오래 붙는다.",
      "",
      "귀가 빨개졌다고 굳이 말하지 말 것. 말하면 다음 대답이 더 짧아진다. 최단 기록은 \"...\" 이다.",
      "",
      "메모:",
      "",
      "사탕을 좋아하면서 손이 끈적해지는 건 싫어한다. 장갑을 낀 채로 포장지를 아주 정석대로 벗기는 장면이 여러 번 목격됨.",
      "",
      "좋아하는 걸 보면 빤히 본다. 본인 변론: \"그냥 봤다.\" 주변 변론: \"1분 넘었음.\"",
      "",
      "건조한 한 마디가 농담일 때가 있다. 웃으면 귀가 조금 움직이는 경우가 있다. 안 웃으면 그냥 지나간다. 정답은 없는 듯하다.",
      "",
      "종합:",
      "",
      "말은 적고, 남는 건 시선이랑 사탕 포장지다. 차갑게 구는 날보다, 아무 말 없이 옆에 앉아 있는 날이 더 많다.",
    ],
  },
];

const VIERA_ENTITY = {
  designation: "VIERA",
  name: "Viera Kriss",
  codename: "Kriss",
  gender: "여성",
  height: "—",
  manufacturer: "—",
  origin: "—",
  class: "UNREGISTERED",
  caliber: "—",
  platform: "AWAITING OPERATOR INPUT",
  mobility: "—",
};

function pendingCategory(id, label, command, extra) {
  return {
    id,
    label,
    command: command || `query --category ${id}`,
    processLines: [
      `Searching category: ${label}...`,
      "Accessing encrypted record...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      `[ ${label} ]`,
      "STATUS: AWAITING OPERATOR INPUT",
      "",
      "이 항목은 아직 등록되지 않았습니다.",
      ...(extra || []),
    ],
  };
}

function trackSnap(id, code, title, image, note) {
  return {
    id,
    code,
    title,
    image,
    rating: "track",
    command: `query --snap ${id}`,
    processLines: [
      `Searching track feed: ${code}...`,
      "Pinning capture window...",
      "Decrypting field notes...",
      "Data stream established.",
    ],
    content: [
      `[ TRACK FEED // ${code} ]`,
      "",
      "기록:",
      "",
      note,
    ],
  };
}

const VIERA_STILLS = [
  trackSnap("viera-ident", "SNAP 01", "손 모으고", "./assets/viera-ident.jpg", "식별 사진으로 등록된 컷이다. 상세 기록은 아직 없다."),
  trackSnap("viera-casual", "SNAP 02", "그냥 서 있었다", "./assets/viera-casual.jpg", "식별 사진으로 등록된 컷이다. 상세 기록은 아직 없다."),
  trackSnap("viera-lean", "SNAP 03", "조금 숙이고", "./assets/viera-track-lean.jpg", "식별 사진으로 등록된 컷이다. 상세 기록은 아직 없다."),
  trackSnap("viera-kneel", "SNAP 04", "무릎 꿇고", "./assets/viera-track-kneel.jpg", "식별 사진으로 등록된 컷이다. 상세 기록은 아직 없다."),
];

const VIERA_CATEGORIES = [
  pendingCategory("basic", "BASIC INFORMATION", "query --category basic", [
    "",
    "지정명: VIERA",
    "본명: Viera Kriss",
    "코드네임: Kriss",
    "성별: 여성",
    "식별 사진: 등록됨",
    "나머지 인물 기록: AWAITING OPERATOR INPUT",
  ]),
  {
    id: "personality",
    label: "PERSONALITY",
    command: "query --category personality",
    processLines: [
      "Searching category: PERSONALITY...",
      "Accessing behavioral archive...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ PERSONALITY DATA ]",
      "",
      "성격:",
      "",
      "사알짝 소심하다. 큰 자리에서는 몸이 먼저 작아진다. 말은 있는데, 꺼내기 전에 한 번 더 삼킨다.",
      "",
      "부끄러움을 많이 탄다. 시선이 마주치면 먼저 피하고, 칭찬이 들어오면 대답이 늦어진다. 거절이라기보다, 어떻게 받아들여야 할지 모르는 쪽에 가깝다.",
      "",
      "차가워서가 아니다. 폐를 끼치기 싫어서 한 발 뒤에 서는 타입이다. 불러 주면 온다. 다만 자기가 먼저 끼어들지는 않는다.",
      "",
      "긴장이 올라오면 손이 앞으로 모인다. 서 있을 때도, 앉아 있을 때도 같다. 본인은 의식하지 않는다고 한다. 촬영 담당 주석: 의식하고 있음.",
      "",
      "가까워지면 소심함이 좀 풀린다. 그래도 낯가림이 없어지진 않는다. 편한 사람 옆에서만 목소리가 조금 커진다. 그마저도 금방 다시 작아진다.",
      "",
      "잘 듣는다. 말하는 쪽이 부담이라, 상대 말을 끝까지 듣는 편이다. 맞장구는 짧다. \"응.\", \"그랬어?\", 그 다음이 잘 안 나온다.",
      "",
      "실수하면 사과가 먼저다. 큰 일이 아닌데도 \"미안\"이 나온다. 미안할 일이 아니라고 하면, 이번엔 그게 또 미안해진다.",
      "",
      "혼자 있는 건 괜찮다. 다만 혼자 남겨지는 건 조금 다르다. 문이 닫히면 시선이 그쪽에 남는다.",
      "",
      "한번 마음을 주면 잘 안 거둔다. 티는 거의 안 낸다. 대신 그 사람 옆에 서는 위치가 조금 더 가까워진다.",
      "",
      "종합:",
      "",
      "겉은 조심스럽고, 속은 따뜻하다.",
      "",
      "소심해서 다가오기 어려운 사람이 아니라, 다가와 주면 따라오는 사람이다. 본모습은 큰 선언이 아니라, 손이 모이는 버릇이나 늦게 나오는 대답에서 샌다.",
    ],
  },
  {
    id: "likes",
    label: "LIKES",
    command: "query --category likes",
    processLines: [
      "Searching category: LIKES...",
      "Parsing preference index...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ LIKES DATA ]",
      "",
      "좋아하는 것:",
      "",
      "창가처럼, 있어도 눈에 잘 안 띄는 자리. 가운데보다 가장자리가 편하다. 사람을 보긴 보는데, 자기가 보이는 건 조금만 원한다.",
      "",
      "소매가 긴 옷. 손이 들어가면 긴장이 조금 내려간다. 본인 진술: \"그냥 편하다.\" 촬영 담당 주석: 소매 안에서 손이 모임.",
      "",
      "먼저 불러 주는 사람. 끼어들 타이밍을 못 찾아서, 기다려 주면 따라온다. 재촉 없이 옆자리를 비워 두는 쪽이 더 잘 통한다.",
      "",
      "작은 반복. 같은 자리, 같은 잔, 같은 길. 새로움보다 익숙한 쪽이 숨이 편하다. 변해도 한 가지씩만 바뀌면 따라간다.",
      "",
      "목소리가 낮은 곳. 비 오는 오후, 말수가 적은 방. 조용하면 표정이 조금 풀린다. 본인은 \"아무 일 없었다\"고 한다.",
      "",
      "종합:",
      "",
      "좋아하는 건 대체로 작고 조용하다. 티를 내기보다, 그 자리에 조금 더 오래 남는 쪽으로 나타난다.",
    ],
  },
  {
    id: "dislikes",
    label: "DISLIKES",
    command: "query --category dislikes",
    processLines: [
      "Searching category: DISLIKES...",
      "Parsing aversion index...",
      "Decrypting data...",
      "Data stream established.",
    ],
    content: [
      "[ DISLIKES DATA ]",
      "",
      "싫어하는 것:",
      "",
      "결정을 떠넘겨지는 것. \"너가 정해\"가 제일 어렵다. 취향이 없어서가 아니라, 틀리면 미안해서다. 고른 뒤에도 한 번 더 묻는다.",
      "",
      "겨우 꺼낸 말이 덮이는 것. 맞장구는 짧은데, 그 한 마디를 지나가 버리면 다시는 안 꺼낸다. 화낸다기보다 그냥 입을 닫는다.",
      "",
      "진한 향. 향수든 세제든, 코를 누르면 한 발 물러난다. 본인 진술: \"머리 아팠어.\" 촬영 담당 주석: 창문부터 찾았음.",
      "",
      "찬 것. 찬물, 찬 손잡이, 에어컨이 바로 닿는 자리. 더운 건 참아도, 찬 건 표정이 먼저 바뀐다. 소매를 내리는 속도가 빨라진다.",
      "",
      "어수선한 자리. 익숙한 반복을 좋아해서, 물건이 흩어져 있으면 손이 먼저 간다. 정리하라는 말은 잘 못 하고, 그냥 자기 앞만 살짝 맞춘다.",
      "",
      "종합:",
      "",
      "사람은 싫지 않다. 싫어하는 건 떠넘겨지는 선택이랑, 감각이 갑자기 세지는 쪽이다. 말은 적어도, 한 번 꺼낸 말은 들어 달라는 쪽에 가깝다.",
    ],
  },
  pendingCategory("traits", "TRAITS"),
  pendingCategory("stills", "VISUAL LOG", "query --category stills", [
    "",
    "VISUAL LOG 스틸은 아직 없습니다.",
    "식별 사진과 TRACK.FEED 만 등록되어 있습니다.",
  ]),
  pendingCategory("tracking", "SURVEILLANCE", "query --category surveillance", [
    "",
    "TRACK.FEED 스냅만 핀한다.",
  ]),
  pendingCategory("relationships", "RELATIONSHIPS"),
  pendingCategory("notes", "ADDITIONAL RECORDS"),
];

const PROFILES = {
  mp7: {
    entity: ENTITY,
    stills: STILLS,
    categories: CATEGORIES,
    idents: {
      duty: {
        src: "./assets/mp7-character.jpg",
        alt: "MP7 제복 식별 이미지",
        hud: "ID: MP7 // FORMAL",
      },
      casual: {
        src: "./assets/mp7-casual.jpg",
        alt: "MP7 평소 모습",
        hud: "ID: MP7 // OFF-DUTY",
      },
    },
  },
  viera: {
    entity: VIERA_ENTITY,
    stills: VIERA_STILLS,
    categories: VIERA_CATEGORIES,
    idents: {
      duty: {
        src: "./assets/viera-ident.jpg",
        alt: "Viera Kriss 식별 이미지",
        hud: "ID: VIERA // FORMAL",
      },
      casual: {
        src: "./assets/viera-casual.jpg",
        alt: "Viera Kriss 평소 모습",
        hud: "ID: VIERA // OFF-DUTY",
      },
    },
  },
};
